# Generated by Django 3.2.13 on 2023-02-15 08:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about_tm_forum', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MarketoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=127)),
                ('view_class', models.CharField(max_length=127)),
                ('request_data', models.BinaryField()),
                ('request_json', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('marketo_request_data', models.JSONField(blank=True, null=True)),
                ('marketo_response_data', models.JSONField(blank=True, null=True)),
                ('marketo_response_code', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontPageSevenTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='seven_top', to='home.frontpage')),
                ('seven_top_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.article')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrontPageSevenSmallLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='seven_small_left', to='home.frontpage')),
                ('seven_small_left_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.article')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrontPageSevenMediumMiddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='seven_medium_middle', to='home.frontpage')),
                ('seven_medium_middle_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.casestudy')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrontPageSevenMediumLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='seven_medium_left', to='home.frontpage')),
                ('seven_medium_left_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.webinar')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrontPageSevenBottomHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='seven_bottom_hero', to='home.frontpage')),
                ('seven_bottom_hero_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.proofofconcept')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('live', models.BooleanField(choices=[(False, 'Draft'), (True, 'Live')], default=False, help_text='Should the advert be showing on the site?')),
                ('url', models.URLField(help_text='Where does clicking on the banner send the user? Usually the advertisers website for eg')),
                ('format', models.CharField(choices=[('billboard', 'IAB Billboard (970x250)'), ('rectangle', 'IAB Medium Rectangle (300x250)')], default='billboard', help_text="The format dictates the position on the homepage, a 'billboard' is horizontal and the rectangle takes up the slot of an article 'card'", max_length=20)),
                ('image', models.ForeignKey(help_text='Please ensure the image is the exact size of the dimensions for the selected format', on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='FrontPageTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(help_text='The image to show in the carousel', on_delete=django.db.models.deletion.PROTECT, to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='home.frontpage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.articletopic')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'unique_together': {('page', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='FrontPageSevenMediumRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='seven_medium_right', to='home.frontpage')),
                ('seven_medium_right_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.article')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'unique_together': {('page', 'seven_medium_right_article')},
            },
        ),
        migrations.CreateModel(
            name='FrontPageReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.frontpage')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.researchreport')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'unique_together': {('page', 'report')},
            },
        ),
        migrations.CreateModel(
            name='FrontPagePopularWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_watch', to='home.frontpage')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.article')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'unique_together': {('page', 'watch')},
            },
        ),
        migrations.CreateModel(
            name='FrontPagePopularRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_read', to='home.frontpage')),
                ('read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.article')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'unique_together': {('page', 'read')},
            },
        ),
        migrations.CreateModel(
            name='FrontPagePopularListen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('listen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.article')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_listen', to='home.frontpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'unique_together': {('page', 'listen')},
            },
        ),
        migrations.CreateModel(
            name='FrontPageHeroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.article')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to='home.frontpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'unique_together': {('page', 'hero')},
            },
        ),
        migrations.CreateModel(
            name='FrontPageFeatured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.article')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='home.frontpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'unique_together': {('page', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='FrontPageAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.author')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='home.frontpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'unique_together': {('page', 'author')},
            },
        ),
    ]
